### ISSUE TITLE
Document section sidebar should be always visible

### ISSUE THREAD

**Issue by sjimenez77** [devonfw/devonfw.github.io#123]
There are some sections in the documentation that are really long. If the user scrolls down but wants to access to another section it has to scroll up and then click on the link of the section that wants to check what makes losing focus completely. For example, if we go to the Cobigen - How To section at https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_how-to.html we can see the follwing page:

![image](https://user-images.githubusercontent.com/2870004/96467301-10390c80-122b-11eb-873b-29cc41ccf302.png)
 
Then the user scrolls down:

![image](https://user-images.githubusercontent.com/2870004/96467557-542c1180-122b-11eb-8676-e8abc88645f5.png)

No sidebar anymore... So if the user wants to check another topic has to scroll up completely and then click on the link. 

This behavior is quite common IMHO and I think that we **must** implement it on our website.

**Comment by sjimenez77** [comment]
I have been playing around a few minutes and I have added some CSS to the sidebar `<div id="toc" class="toc2">` in the browser inspector:

```css
    position: fixed;
    width: 25vw;
    top: 60px;
    margin-left: 2vw;
```

And it looks more or less good. Obviously we would need to fix the behaviour for other screen devices, but could be a starting point.

**Comment by suprishi** [comment]
Rest 1
