### ISSUE TITLE
Tables in docs exceed page limit

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#126]
### Expected behavior

As a user of the devonfw IDE, I want to read the java command docs so that I can use it properly.

### Actual behavior

I cannot read the whole table contents in this section: https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Go To https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc
2. Check the first table. The table should have line wrapping enable as currently its having a horizontal scrollbar and even the text is cut at some length.

### Affected version:

* OS: Windows
* Browser: Firefox

**Comment by ssarmokadam** [comment]
merged PR and changes are reflecting on website
