### ISSUE TITLE
Styling of search quick results broken

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#13]
### Expected behavior

As a website visitor, I want to quickly get an overview of my search results so that I can directly navigate to the one of my choice.

### Actual behavior

I get search quick results in an overlay, which anyhow are not readable as of odd word wrap and styling:
![grafik](https://user-images.githubusercontent.com/1427255/65240092-c2f6e280-dae0-11e9-8c29-4bdba3b267e6.png)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Go to https://www.devonfw.com/devonfw-official-website/website/pages/docs/page-docs.html
2. Select Getting Started -> devonfw Introduction
3. Go to search bar on top right and search for "architecture"

### Affected version:

* OS: Windows
* Browser: Firefox

**Comment by jambulud** [comment]
Hi,
Do you still get this error? I have checked it in firefox using different screen resolutions but it is working correctly for me.

**Comment by maybeec** [comment]
Hi, it seems to be partially fixed.
The popup does not seem to have a background, which makes it overlay with the underlying text, i.e. the right menu.

![grafik](https://user-images.githubusercontent.com/1427255/65304880-0c4b3e80-db82-11e9-90e0-ede98c80845e.png)
