### ISSUE TITLE
Html bookmarks are not changing in URL

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#14]
### Expected behavior

As a website visitor, I want to navigate in the docs section and pass my colleague a link to the current chapter I was reading so that he can follow up on this.

### Actual behavior

Clicking through the menu on the left and on the right seems not to change any of the bookmark references in the URL. It  seems that the page gets broken based on this. Removing the persisted bookmark of the URL finally also restores some odd behavior

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Changing the chapter on the left menu does not change anything in the URL
2. Clicking the chapter on the right changes the URL to add the bookmark to be shown
3. Clicking on the left menu again will not remove the bookmark at all.

### Affected version:

* OS: Windows
* Browser: Firefox

**Comment by jambulud** [comment]
Hi,
Do you still get this error? I have checked it in firefox using different screen resolutions but it is working correctly for me.

**Comment by maybeec** [comment]
The current issue is, that asciidoc is just generating on master file, which maintains it's documents links just by bookmarks as all links are intended to be on the same site.

There is an approach to overcome this by an additional extension: 
https://github.com/asciidoctor/asciidoctor/issues/626#issuecomment-418441492
which can be loaded also by asciidoctorj:
https://discuss.asciidoctor.org/Maven-plugin-and-extensions-td3149.html

Anyhow, this plugin is meant to be compatible to 1.5.7.1 and we have to use 1.5.8 as of another bug breaking our build while implementing the custom templates (asciidoctor-backend)

**Comment by maybeec** [comment]
Additional links:

AsciidoctorJ AST:
https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#understanding-the-ast-classes
AsciidoctorJ 1.5.8 AST implementation:
https://github.com/asciidoctor/asciidoctor/blob/v1.5.8/lib/asciidoctor/abstract_node.rb
How to debug Ruby with vsCode:
https://dev.to/dnamsons/ruby-debugging-in-vscode-3bkj
