### ISSUE TITLE
Remove numbers in Docs section

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devonfw.github.io#141]
As a website user, I want no numbers in front of the headlines of the menu in the docs section so that I can find the things I am looking for more easily.

**Comment by SchettlerKoehler** [comment]
Check if "-a sectnums=false" is working

**Comment by SchettlerKoehler** [comment]
It looks like removing :sectnums: from https://raw.githubusercontent.com/devonfw/devonfw-guide/master/master.asciidoc could fix this issue.

**Comment by SchettlerKoehler** [comment]
Other master files also have this setting -> remove them

**Comment by maybeec** [comment]
Might it be an option to let a script cleanup all the secnum config before generating the website? Otherwise we might interfere with other docs users generating pdf files which want to have secnums. (just thinking out loud)

**Comment by SchettlerKoehler** [comment]
That sounds good. With that, we also would make sure that in the future no one will add a secnum by accident because of copying and pasting stuff.

**Comment by SchettlerKoehler** [comment]
:partnums: needs also be removed
