### ISSUE TITLE
Change the page title

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#15]
As a browser user, I want easily see based on the tab name which side I am in so that I can navigate quickly through my tabs.
Therefore, please provide the following schema to the page title shown in the tab: "devonfw - <placehodler for page/chapter name>"

**Comment by jambulud** [comment]
So basically, in tab;
landing page --> devonfw - landing
explore page --> devonfw - explore
community page --> devonfw - community
resources page --> devonfw - resources
docs page --> devofw - docs

I'm a bit confused about the "page/chapter". Do you mean something like "devonfw - docs/architecture" if you have clicked on architecture in docs architecture chapter?

**Comment by maybeec** [comment]
Hi exactly, I would take a pattern like

`devonfw` for landing page
and `devonfw - <page>/<chapter>/<section>` or leave section away if it is too complicated.
`<chapter>` is the left menu, `<section>` is the right menu of docs section

**Comment by jambulud** [comment]
Okay, understood. I give this task and estimation of 3 hours, changing the title for landing, explore, community abd resources is trivial, but docs is a bit more complicated.
