### ISSUE TITLE
Evaluate antora

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devonfw.github.io#150]
As a website developer, I want an easy generation of the website so that I can fix errors easily.

Please check if antora.org could be a replacement for the current generation process of the website or only the docs section. Please also check if this would solve other issues in the backlog. The result of this issue should be a comparison of the existing approach and antora

**Comment by yF-B** [comment]
If we want use Antora, we need to make a lot of changes, because it uses a different structure than the one we currently use.
