### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devonfw.github.io#152]
To be compliant with the intended design of the website the font should be changed to the font ubuntu (except the code snippets).

https://projects.invisionapp.com/share/Q9SVP1BR8ZF#/screens
https://fonts.google.com/specimen/Ubuntu

**Comment by SchettlerKoehler** [comment]
In the "Table of Contents" in the docs the font-style is italic. Please remove this.

**Comment by yF-B** [comment]
Rest 1
