### ISSUE TITLE
Remove links

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devonfw.github.io#154]
As a devonfw architect, I want to remove links to pages that have no up-to-date content so that the website looks professional.

Remove the links to Ressources and Community in the header.

**Comment by priyanshk20** [comment]
Can I do this?

**Comment by SchettlerKoehler** [comment]
Of course. Just fork the repository and create a PR.

**Comment by priyanshk20** [comment]
Can you please tell the file I have to edit, I am not able to find that.

**Comment by SchettlerKoehler** [comment]
https://github.com/devonfw/devonfw.github.io/blob/develop/website/components/header/header.asciidoc

**Comment by priyanshk20** [comment]
Made a PR. @SchettlerKoehler

**Comment by SchettlerKoehler** [comment]
Closed by #157
