### ISSUE TITLE
Wrong folders in architectures/solution

### ISSUE THREAD

**Issue by tobka777** [devonfw/devonfw.github.io#227]
During my local testing, I noticed that the folders in my architectures/solution are not the same as in the architectures repository (https://github.com/devonfw/architectures). This corresponds to wrong links for `microsvc_platforms_azure` (instead of `microsvc_platforms`) and `provisioning_azure_devops` (instead of `provisioning_azure_azuredevops`).

**Comment by yF-B** [comment]
Please synchronize the forked repository before you want to change something
