### ISSUE TITLE
New concept for links on welcome page

### ISSUE THREAD

**Issue by cinnamon-coder-hub** [devonfw/devonfw.github.io#264]
This issue concerns the "learn more" links on the WelcomePage (see red labeled position on picture)
![linksWelcomePage.png](https://images.zenhubusercontent.com/6194edac0f22bb7f6134c759/799b4067-f062-4833-af28-73833cb696c0). 
Some links could fit better to the texts advertising them.
For example under "Source of Knowledge" where tutorials or guides would be expected by an user, the link 
https://devonfw.com/website/pages/docs/master-release-notes.asciidoc.html
directs the user to a list of release Notes
![grafik.png](https://images.zenhubusercontent.com/6194edac0f22bb7f6134c759/76f10d9b-3618-4d43-8f64-63d0eb4d8d95).
The Link to the "Getting Started" page 
https://devonfw.com/website/pages/docs/getting-started.asciidoc.html
may be a better option? There is an introduction about what devonfw is as well as some guides. Please participate in this discussion by sharing opinions, ideas or alternative links regarding the links mentioned above.

**Comment by maybeec** [comment]
My proposals:

* Architecture flexibility: I would strongly recommend to either have a new landing page about architecture for all stacks, or have multiple buttons here besides `learn more...` only, which actually link the different architecture guides:
  * devon4ng: https://devonfw.com/website/pages/docs/master-devon4ng.asciidoc_architecture.html
  * devon4node: https://devonfw.com/website/pages/docs/devon4node-architecture.asciidoc.html
  * devon4j: https://devonfw.com/website/pages/docs/devon4j.wiki_architecture.asciidoc.html
  * devon4net: https://devonfw.com/website/pages/docs/architecture_guide.asciidoc.html
* Source of Knowledge: for the moment https://devonfw.com/website/pages/docs/introduction-why-should-i-use-devonfw.asciidoc.html, but needs to be changed as soon as we have the separate page addressing this topic directly @SchettlerKoehler 
* No license traps: https://devonfw.com/website/pages/docs/master-solicitor.asciidoc_introduction.html
* Support & Community: for the moment https://devonfw.com/website/pages/docs/further-info-community-links.asciidoc.html, but should be different in the future if we have a separate page for it @SchettlerKoehler 
* Constantly evolving: actually not sure, whether this collides with "source of knowledge" - let's remove learn more for the moment.
* Rich documentation: I don't like it - could be also meant like "too big" Maybe we can rename it to "Strong Guidelines" and link it to the docs section https://devonfw.com/website/pages/docs/master.html OR even removing it for now and adding here the solution browser @SchettlerKoehler, what do you think? Shouldn't we release the solution browser already now and make it available here as a pillar?

**Comment by SchettlerKoehler** [comment]
@maybeec The links a looking good for the moment. 
"Strong Guidelines" feels a bit fuzzy. Maybe we can use something like "helpful documentation". Something that says that we are proud of the content of the documentation.
Regarding the release of the solution browser, I would wait for the renaming and changing of the URL (https://github.com/devonfw/architectures/issues/83)

**Comment by maybeec** [comment]
I think my intend was a little different. With strong guidelines I meant the idea to have something concrete to steer developers with instead of simply putting a book of documentation on the table and saying 'find the best solution'.

**Comment by SchettlerKoehler** [comment]
I see this point, but for me, "guidelines" does not cover the complete thing we are offering. But maybe this is not necessary. We can start with "Strong Guidelines" and see how it feels.
