### ISSUE TITLE
Images are not shown at the deployed page

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#3]
see https://www.devonfw.com/devonfw-official-website/website/pages/logo/page-logo.html

**Comment by jambulud** [comment]
Fixed
Resources page:

![images shown in resources page](https://user-images.githubusercontent.com/43032659/65306397-8a5d1480-db85-11e9-91ee-8aa054db8d28.png)

logo page:

![logo page images ](https://user-images.githubusercontent.com/43032659/65306446-a6f94c80-db85-11e9-90d2-3b66f7bb0e67.png)

**Comment by maybeec** [comment]
Mh images are not in /docs section:
see I: getting started -> 3. download and setup
