### ISSUE TITLE
Identify an alternate to docgen for website generation

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devonfw.github.io#336]
Evaluate different tools and find alternatives to docgen for devonfw website generation, keeping in mind how the current implementation(docgen processing) is happening. 

Acceptance Criteria:
1. Document the comparison of docgen with different tools. 
2. Recommend one tool/software after discussing with team/onsite counterparts.

**Comment by ssarmokadam** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/devonfw.github.io/336?planning-poker) with ZenHub @prathibhapadma

**Comment by sujith-mn** [comment]
Antora is replacing docgen
