### ISSUE TITLE
References to github files

### ISSUE THREAD

**Issue by jambulud** [devonfw/devonfw.github.io#77]
As a user, I want to have links in documentation files referencing themselves (its github url) so that when I see these file in the website I can click its link, go to github and modify the file.

Nowadays when you find an error through the website, you don't know which file to modify so it is difficult to contribute.

**Comment by maybeec** [comment]
We should have a pencil next to chapters/sections, which you could click on and finally jump to github to the right section, so you could directly adapt it.
I even thought of embedding github in an iframe (if possible) and provide a custom banner on the top, which even provides a 3-step guide how to really do the adaptions on github as most of the people don't know how easy it is and that they cannot break anything.

**Comment by SchettlerKoehler** [comment]
This was already done
