### ISSUE TITLE
Introduce mechanism for network internal website additions

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#8]
For internal website content, we should provide a mechanism like implemented here: 
https://github.com/devonfw/devonfw-website/blob/b07e310e19a4b4610ef3ea9bf5a531949be6d834/dist/javascript/main.js#L45

which hides menu entries or html elements if it's content could not be loaded.

**Comment by jambulud** [comment]
> For internal website content, we should provide a mechanism like implemented here:
> https://github.com/devonfw/devonfw-website/blob/b07e310e19a4b4610ef3ea9bf5a531949be6d834/dist/javascript/main.js#L45
> 
> which hides menu entries or html elements if it's content could not be loaded.

The link is not working, could you please update it?

**Comment by maybeec** [comment]
It's in a private repository. I enabled the link for you.

**Comment by jambulud** [comment]
Now I can see it.
I think it is not a difficult task, My guess is that it would take three, at most four hours to add the mechanism in every place that it needs to be and also check that everything works correctly

**Comment by SchettlerKoehler** [comment]
This is possible by adding the URL of a server providing the snippets to this array: https://github.com/devonfw/devonfw.github.io/blob/develop/asciidoctor-backend/erb/html5/document.html.erb#L217
You can then add
```
[.internal]
nameOfTheSnippet
```
to the asciidoc files and the website will load and include `<your URL>/<nameOfTheSnippet>/index.html` at this position.
