### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by jambulud** [devonfw/devonfw.github.io#88]
As a programmer that spends all the day with the PC, I want a button to enable night mode so that my eyes can rest

**Comment by maybeec** [comment]
I don't think there is any need here. Asciidoc already comes with the styles and there are browser plugins like https://addons.mozilla.org/de/firefox/addon/dark-mode-webextension/ which provide this for you automatically. Our website seems to be fine with respect to the stylings and the texts but obviously images are not covered by that. I think we cannot prevent from it in general as you would have to provide dark versions of all images simultaneously (so maybe out of scope for the moment)
