### ISSUE TITLE
selected headline not shown in docs - confusing the user

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#93]
### Expected behavior

As a user , I want to click on a chapter on the left docs section toc so that I can jump to the chapter start reading at the headline selected.

### Actual behavior

The browser jumps to the correct section, but the header is overlaying the headline selected. 

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. go to https://devonfw.com/website/pages/docs/master-devon4j.asciidoc_guides.html#guide-dependency-injection.asciidoc
2. the headline is not shown as it is overlayed by the header

### Comments/Hints:
The header seems to be styled as an overlay as it is bound to the top of the browser window and not to the top of the page, which is fine. But we have to check whether we can align the jump function for bookmarks accordingly in this regard.

### Affected version:

* OS: Windows
* Browser: Firefox

**Comment by jambulud** [comment]
I will leave this to remember where to find suitable solutions:

https://css-tricks.com/hash-tag-links-padding/
